### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by creatyvtype** [DBC-SF/mentorship-wiki#5]
I am excited about the implementation of this application and I really think it will be a huge improvement over google maps, but I really did not appreciate the way it was implemented. We received absolutely no notice and then it was live. This led to a mass signup session and within 2 hours every last available session was completely booked. These were blocks that were not only different from the previous schedule, but some of us had already signed up for hours on the previous calendar for this coming session according to the signup schedule we've all agreed to be using. I planned my entire next 3 weeks around it, and it all just fell apart without notice. I would like to formally request that Dev Bootcamp honor the sessions that were signed up for the coming phase from the previous calendar.

Also, the structured tiers of signing up based on employment status has disappeared, PLEASE bring that back.

I love the visibility of who signed up for what, and I'm seeing abuse of signups. One person, for example, signed up for 8 straight hours on weekends, and that just doesn't seem right. Wasn't there originally a limit to how many sessions we could sign up for at once? Is there a way for Deputy to prevent people from signing up for too many sessions in a row, in a week, or in a phase?

Majd

**Comment by bootcoder** [comment]
1st: Heard

2nd: I'd like to think this wasn't a complete surprise. I sent an email on the 30th with a heads up that scheduling would be changing.

3rd: You're right about employed signup. I haven't found a good way to accomplish this with Deputy until literally right now. It just occurred to me, I could add a training requirement to night and weekend shifts for employed mentors which I could then remove after a certain point, like 72 hours..... Pretty sure that would do the trick without being a total pain in the ass. Unfortunately we'll have to wait two weeks to test. But I'll go ahead and document it in the wiki now. 

4th: You are totally correct about old shifts: I will update the wiki with the following:

"Any shifts scheduled by night and weekend mentors under the old calendar for the upcoming phase will be honored under the new schedule for this phase only. Simply signin for the shift as an unscheduled shift and leave a note when signing out that the shift was previously scheduled."

**Comment by creatyvtype** [comment]
Aha. I overlooked the email because the subject was "DBC Closed July 4th week". So does this mean that you will not be deleting the calendar until the end of the phase? Because I had signed up for shifts for the whole phase and most of those were taken are now only reflected on the old calendar. If you delete the calendar, it will delete the shifts on my google calendar.

On that note, is there a way for these Deputy shifts to be reflected in my own google calendar? Haven't seen a way to import the calendar.

I am completing my second shift today then since I had originally signed up for 2-5 for today and there are no other mentors present.

Can you please add me to the Github group so that I can complete code reviews?

Also, I DO see my smiling face on the Infowall! Cool!

**Comment by bootcoder** [comment]
Noted, I will leave the calendar in place until the end of the phase. 

As to the calendar integration the answer is yes, the implementation is shit. I'm working on it.

**Comment by creatyvtype** [comment]
Thanks Hunter! Good work :-)

Majd
